#!/usr/bin/env bash
# Install nginx on your web-01 server

# Update package lists for upgrades and new package installations
sudo apt-get update -y

# Unstall Nginx
sudo apt-get install -y nginx

# Configure Nginx to listen on port 80 and serve a "Hello World!" page
echo "server {
	listen 80;
	listen[::]:80;
	server_name _;

	location / {
		echo "Hello World!"
	}
}" > /etc/nginx/sites-available/default

# Restart Nginx
sudo service nginx restart

