#!/usr/bin/env bash
# Install nginx on your web-01 server

# Update package lists for upgrades and new package installations
sudo apt-get update -y

# Unstall Nginx
sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index > /dev/null

# Restart Nginx
sudo service nginx restart

