#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.

# Install HAProxy
if [ ! -e haproxy];then
	sudo apt -y -s install haproxy
fi

# Update system
sudo apt -s -y update

# start HAProxy
sudo service haproxy start

# edit the default settings haproxy
sudo sed -i '$a\ENABLED=1' /etc/default/haproxy

# set HAProxy configurations
sudo sed -i '$a\\n' /etc/haproxy/haproxy.cfg

cat > /etc/haproxy/haproxy.cfg << _EOL_
global
        log /dev/log    local0
        log /dev/log    local1 notice
        chroot /var/lib/haproxy
        stats socket /run/haproxy/admin.sock mode 660 level admin
        stats timeout 30s
        user haproxy
        group haproxy
        daemon

        # Default SSL material locations
        ca-base /etc/ssl/certs
        crt-base /etc/ssl/private

        # Default ciphers to use on SSL-enabled listening sockets.
        # For more information, see ciphers(1SSL). This list is from:
        #  https://hynek.me/articles/hardening-your-web-servers-ssl-ciphers/
        ssl-default-bind-ciphers ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:ECDH+3DES:DH+3DES:RSA+AESGCM:RSA+AES:RSA+3DES:!aNULL:!MD5:!DSS
        ssl-default-bind-options no-sslv3

defaults
        log     global
        mode    http
        option  httplog
        option  dontlognull
        timeout connect 5000
        timeout client  50000
        timeout server  50000
        errorfile 400 /etc/haproxy/errors/400.http
        errorfile 403 /etc/haproxy/errors/403.http
        errorfile 408 /etc/haproxy/errors/408.http
        errorfile 500 /etc/haproxy/errors/500.http
        errorfile 502 /etc/haproxy/errors/502.http
        errorfile 503 /etc/haproxy/errors/503.http
        errorfile 504 /etc/haproxy/errors/504.http

frontend patoski
        bind *:80
	mode http
        default_backend my_servers

backend my_servers
	balance roundrobin
        server 305199-web-01 35.175.128.192:80
        server 305199-web-02 54.88.205.156:80

_EOL_

# reload and restart HAProxy
sudo service haproxy reload
