#!/usr/bin/env bash
#Requirements: Using what you did for task #0, make your fix short and sweet.
rm /etc/nginx/sites-enabled/default
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/
sudo service nginx restart
