#!/usr/bin/env bash
#Requirements: Using what you did for task #0, make your fix short and sweet.
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/
service nginx restart
service nginx stop
