#!/usr/bin/env bash
# Fixes a web server to run Nginx as user listening on all IPs on port 8080.
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sed -i "s/listen 80;/listen 8080;/g" /etc/nginx/sites-available/default
sed -i "s/listen [::]:80;/listen [::]:8080;/g" /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
sudo -u nginx service nginx start
