#!/bin/bash

# Set the path to the private key
private_key="~/.ssh/school"

# Set the server address
server_address=34.229.189.4

# Set the username
username="ubuntu"

# SSH connection using the private key
ssh -i $private_key $username@$server_address
